### ISSUE TITLE
建议引入lodash的set进行对象的构建,或者使用[]代替.运算符

### ISSUE THREAD

**Issue by jueinin** [PsChina/convert-excel-js#1]
目前的eval方法,遇见key是个字符串的情况就直接报错了,因为点操作符对字符串的支持性很差,带有空格之类的就挂了.

![test](https://user-images.githubusercontent.com/22928234/62376897-4893f280-b574-11e9-8336-866df3d483d9.png)

**Comment by PsChina** [comment]
请给出报错的 excel 文件或者仓库 url 。

**Comment by PsChina** [comment]
已支持在 [098ffb0](https://github.com/PsChina/convert-excel-js/commit/098ffb0f0793370d1fb5ff1f604847c62f780101)
